spring:
  application:
    name: oauth-client-demo

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
          complete-github:
            provider: my-github
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
            redirect-uri: http://localhost:8080/login/oauth2/code/github
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            client-name: Complete Github Client Registration

        provider:
          my-github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

logging:
  level:
    org.springframework.security: TRACE